In [3]:
import torch
torch.__version__

'1.13.1'

In [7]:
x = torch.zeros(4, 2, dtype = torch.long)
print(x)
y = torch.rand(4, 2)
print(y)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])
tensor([[0.5876, 0.0332],
        [0.3397, 0.6286],
        [0.6195, 0.2746],
        [0.9007, 0.8135]])


In [8]:
ft = torch.FloatTensor([1,2,3])
print(ft)

tensor([1., 2., 3.])


In [9]:
import math

a =torch.rand(1,2) * 2 - 1

In [10]:
print(a)

tensor([[0.1738, 0.2188]])
